[package]
name = "live-collab"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "live-collab-sender",
    "live-collab-receiver",
    "shared",
]

[dependencies]
nih_plug_xtask = { git = "https://github.com/robbert-vdh/nih-plug.git" }
